language: php

matrix:
  include:
    - php: 5.3
      env: IGNORE_PLATFORM=yes
    - php: 5.4
      env: IGNORE_PLATFORM=yes
    - php: 5.5
      env: IGNORE_PLATFORM=yes
    - php: 5.6
    - php: 7
      env: LINT=yes QA=yes
    - php: 7.1
    - php: hhvm
      dist: trusty
      sudo: required
      env: IGNORE_PLATFORM=yes
    - php: nightly
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: hhvm

install:
  - composer selfupdate
  - if [ "$LINT" == "yes" ]; then composer global require --update-no-dev sugared-rim/cs; fi
  - if [ "$IGNORE_PLATFORM" == "yes" ]; then composer install --no-dev --ignore-platform-reqs; else composer install --no-dev; fi
  - composer dump-autoload
  - if [ "$QA" == "yes" ]; then composer global require --update-no-dev codeclimate/php-test-reporter:dev-master satooshi/php-coveralls; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

script:
  - composer travis
  - if [ "$LINT" == "yes" ]; then composer lint; fi

after_success:
  - if [ "$QA" == "yes" ]; then coveralls -v; fi
  - if [ "$QA" == "yes" ]; then test-reporter; fi
